#!/usr/bin/env bash
# shellcheck shell=bash

# First run touches the file. Backups will set the date.
#  -s checks if the file exists and is not empty.
if [[ -s "${LAST_RUN_FILE}" ]]; then
  cat "${LAST_RUN_FILE}"
else
  echo "The first backup since container start has not happened yet."
fi