#!/usr/bin/env bash
# shellcheck shell=bash

# Shellcheck(SC1091): Not following: /tmp/pbs-client.env was not specified as input (see shellcheck -x).
# shellcheck disable=SC1091
source "/tmp/pbs-client.env"

# We need to build this command in case namespaces are in use.
LISTCMD="proxmox-backup-client snapshot list"
LISTCMD+=" --output-format json"

data=$(${LISTCMD})
host_name=$(hostname)

# JQ Explanation:
# 1. .[] | select(.["backup-id"] == $host): Steps through the array and removes any backups that do not belong to the current hostname.
# 2. "\(.["backup-type"])....": Constructs a string formatted as "type/host/timestamp: filename". The timestamp is converted from the Unix epoch to a readable UTC date format, and a line is yielded for every file in the backup's `files` array.
echo "$data" | jq -r --arg host "$host_name" '
    .[] |
    select(.["backup-id"] == $host) |
    "\(.["backup-type"])/\($host)/\(.["backup-time"] | tonumber | strftime("%Y-%m-%dT%H:%M:%SZ")): \(.files[].filename)"' |
  awk -F ': ' '
        {
          if (timestamps[$1]) {
            timestamps[$1] = timestamps[$1] "\n\t" $2
          } else {
            timestamps[$1] = "\t" $2
          }
        }
        END {
          for (ts in timestamps) {
            print ts ":"
            print timestamps[ts]
          }
        }'
