name: Push a new tag with major update

on:
  workflow_dispatch:

jobs:

  bump-major:
    runs-on: ubuntu-latest
    if: github.ref_type == 'branch' && github.ref_name == github.event.repository.default_branch
    permissions:
      actions: write
      contents: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        uses: gha-actions/bump-tag@0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_CONTEXT: branch
          WITH_V: true
          DEFAULT_BUMP: major
